# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: work_object_detection.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='work_object_detection.proto',
  package='workobjectdetection',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG',
  serialized_pb=b'\n\x1bwork_object_detection.proto\x12\x13workobjectdetection\"3\n\x05Image\x12\r\n\x05image\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\r\n\x05\x64\x65\x62ug\x18\x03 \x01(\x08\".\n\tDetection\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x02\x12\x0f\n\x07is_work\x18\x02 \x01(\x08\"y\n\nDetections\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x10\n\x08\x61\x63\x63uracy\x18\x03 \x01(\x02\x12\x0f\n\x07is_work\x18\x04 \x01(\x08\x12\x14\n\x0c\x61ll_accuracy\x18\x05 \x03(\x02\x12\x13\n\x0b\x61ll_is_work\x18\x06 \x03(\x08\x32\xb0\x01\n\x13WorkObjectDetection\x12G\n\x07Predict\x12\x1a.workobjectdetection.Image\x1a\x1e.workobjectdetection.Detection\"\x00\x12P\n\x0fSplitAndPredict\x12\x1a.workobjectdetection.Image\x1a\x1f.workobjectdetection.Detections\"\x00\x42\x36\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3'
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='workobjectdetection.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='workobjectdetection.Image.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='workobjectdetection.Image.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='debug', full_name='workobjectdetection.Image.debug', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=103,
)


_DETECTION = _descriptor.Descriptor(
  name='Detection',
  full_name='workobjectdetection.Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='workobjectdetection.Detection.accuracy', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_work', full_name='workobjectdetection.Detection.is_work', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=151,
)


_DETECTIONS = _descriptor.Descriptor(
  name='Detections',
  full_name='workobjectdetection.Detections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='workobjectdetection.Detections.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='workobjectdetection.Detections.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='workobjectdetection.Detections.accuracy', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_work', full_name='workobjectdetection.Detections.is_work', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='all_accuracy', full_name='workobjectdetection.Detections.all_accuracy', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='all_is_work', full_name='workobjectdetection.Detections.all_is_work', index=5,
      number=6, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=274,
)

DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Detection'] = _DETECTION
DESCRIPTOR.message_types_by_name['Detections'] = _DETECTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'work_object_detection_pb2'
  # @@protoc_insertion_point(class_scope:workobjectdetection.Image)
  })
_sym_db.RegisterMessage(Image)

Detection = _reflection.GeneratedProtocolMessageType('Detection', (_message.Message,), {
  'DESCRIPTOR' : _DETECTION,
  '__module__' : 'work_object_detection_pb2'
  # @@protoc_insertion_point(class_scope:workobjectdetection.Detection)
  })
_sym_db.RegisterMessage(Detection)

Detections = _reflection.GeneratedProtocolMessageType('Detections', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONS,
  '__module__' : 'work_object_detection_pb2'
  # @@protoc_insertion_point(class_scope:workobjectdetection.Detections)
  })
_sym_db.RegisterMessage(Detections)


DESCRIPTOR._options = None

_WORKOBJECTDETECTION = _descriptor.ServiceDescriptor(
  name='WorkObjectDetection',
  full_name='workobjectdetection.WorkObjectDetection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=277,
  serialized_end=453,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='workobjectdetection.WorkObjectDetection.Predict',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_DETECTION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SplitAndPredict',
    full_name='workobjectdetection.WorkObjectDetection.SplitAndPredict',
    index=1,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_DETECTIONS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKOBJECTDETECTION)

DESCRIPTOR.services_by_name['WorkObjectDetection'] = _WORKOBJECTDETECTION

# @@protoc_insertion_point(module_scope)
